USE [master]
GO

/****** Object:  Database [BookManagement]    Script Date: 22/09/2020 23:55:35 ******/
CREATE DATABASE [BookManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BookManagement.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BookManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BookManagement_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BookManagement] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookManagement] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BookManagement] SET  MULTI_USER 
GO

ALTER DATABASE [BookManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookManagement] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BookManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BookManagement] SET  READ_WRITE 
GO

